backend/models/Host.php
<?php
namespace backend\models;
 
use Yii;
use common\models\Chat;
 
class Host extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hosts';
    }
     
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
           [['email','first_name', 'last_name'], 'required'],
            ['email', 'email'],
            [['first_name', 'last_name'], 'string', 'max' => 255]
            
          
        ];
    }

    public function getChat()
    {
        return $this->hasOne(Chat::className(), ['ID' => 'Chat']);
    }
 

      public function getProfile()
    {
        return $this->hasOne(Profile::className(), ['public_email' => 'email']);
    }

       public function getCeoString()
      {
        
      return $this->first_name . " " . $this->last_name ;
           
      }

       public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }
}

backend/controllers/HostController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Host;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ChatController implements the CRUD actions for Chat model.
 */
class HostController extends Controller
{

    public function actionIndex()
    {
      
        $review = Host::find()->all();
         
        return $this->render('index', ['model' => $review]);
    }

  public function actionCreate()
    {
        $model = new Host();
 
        // new record
        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(['index']);
        }
                 
        return $this->render('create', ['model' => $model]);
    }

     /**
     * Edit
     * @param integer $id
     */
    public function actionEdit($id)
    {
        $model = Host::find()->where(['id' => $id])->one();
 
        // $id not found in database
        if($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');
         
        // update record
        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(['index']);
        }
         
        return $this->render('update', ['model' => $model]);
    }  


    /**
     * Delete
     * @param integer $id
     */
     public function actionDelete($id)
     {
         $model = Host::findOne($id);
         
        // $id not found in database
        if($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');
             
        // delete record
        $model->delete();
         
        return $this->redirect(['index']);
     } 


}

backend/views/host/_form.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Edition;
use common\models\Chat;
use dosamigos\datepicker\DatePicker;
use dosamigos\ckeditor\CKEditor;
use kartik\time\TimePicker;
use frontend\models\User;


/* @var $this yii\web\View */
/* @var $model common\models\Chat */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="chat-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
    ]); ?>
   
        <?= $form->field($model, 'first_name')->textInput() ?>

        <?= $form->field($model, 'last_name')->textInput() ?>

         <?= $form->field($model, 'email')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/host/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ChatSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="chat-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID') ?>

    <?= $form->field($model, 'Edition') ?>

    <?= $form->field($model, 'ChatDate') ?>

    <?= $form->field($model, 'StartTime') ?>

    <?= $form->field($model, 'EndTime') ?>

    <?php // echo $form->field($model, 'Topic') ?>

    <?php // echo $form->field($model, 'Host') ?>

    <?php // echo $form->field($model, 'Description') ?>

    <?php // echo $form->field($model, 'Status') ?>

    <?php // echo $form->field($model, 'Log') ?>

    <?php // echo $form->field($model, 'Podcast') ?>

    <?php // echo $form->field($model, 'ParticipantsLimt') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/host/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = 'Create Review Questions';
$this->params['breadcrumbs'][] = ['label' => 'Review', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/host/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Edition;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ChatSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Chat Host\'s';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Add a Host', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

      <table border="1" class="table table-striped table-bordered">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Actions</th>
    </tr>
    <?php foreach($model as $field){ ?>
    <tr>
        
        <td><?= $field->first_name; ?></td>
        <td><?= $field->last_name; ?></td>
        <td><?= $field->email; ?></td>
        <td><?= Html::a("Edit", ['host/edit', 'id' => $field->id]); ?> | <?= Html::a("Delete", ['host/delete', 'id' => $field->id]); ?></td>
    </tr>
    <?php } ?>
</table>
</div>

backend/views/host/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = 'Update Review Question: ' . ' ' . $model->ID;
$this->params['breadcrumbs'][] = ['label' => 'Review', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID, 'url' => ['view', 'id' => $model->ID]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="chat-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/host/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use frontend\models\User;

/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = $model->ID;
$this->params['breadcrumbs'][] = ['label' => 'Chats', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->ID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->ID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'ID',
            [                      // the owner name of the model
                'label' => 'Edition',
                'value' => $model->edition->EditionName,
            ],            
            'ChatDate',
            'StartTime',
            'EndTime',
            'Topic',
            [                      // the owner name of the model
                'label' => 'Host',
                'value' => $model->host->CeoString,
            ], 
            'Description:ntext',
            [                      // the owner name of the model
                'label' => 'Status',
                'value' => $model->chatStatus($model->Status),
            ],
            'Log',
            'Podcast',
            'ParticipantsLimt',

            
        ],
    ]) ?>

</div>